### ISSUE TITLE
Error in PHPStorm then installing plugin

### ISSUE THREAD

**Issue by klodoma** [cedricziel/idea-xliff#2]
The IDE reports an error when installing this plugin:

![screenshot_5](https://user-images.githubusercontent.com/944350/33543202-74d25f16-d8d6-11e7-996a-5915ff407731.png)

```


null
java.lang.AbstractMethodError
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.supportsDumbModeFolding(FoldingUpdate.java:211)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.b(DocumentFoldingInfo.java:300)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:288)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:353)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:69)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.a(HistoryEntry.java:219)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.createHeavy(HistoryEntry.java:120)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager.a(EditorHistoryManager.java:307)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:359)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:197)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:415)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cedricziel** [comment]
What version of PHPStorm are you using?

**Comment by klodoma** [comment]
Hi, sorry, for the missing details, I hit the save button to early, I've updated the comment. Let me know if more info is required.

**Comment by cedricziel** [comment]
Alright, thx for the update - I guess that's enough! :)

**Comment by cedricziel** [comment]
I removed the custom fileview for the 2017.3 platform. It should work ootb with v0.0.4. Thx for the report!
